### PR TITLE
add --sedbin to specify alternative sed executable

### PR DESCRIPTION
**Pull request by clarkwang**
For https://github.com/aureliojargas/sedsed/issues/72

### CODE REVIEW

**Comment by aureliojargas** [comment]
Hi @clarkwang, thank you very much for your contribution, I think `--sedbin` will be a nice improvement.

Could you please remove the `-E` commit from this PR, so this one stay focused in the `--sedbin` part?

**Comment by clarkwang** [comment]
I don't know how. I made the `-E` change after sending the first pull request. I don't understand why it include both commits here.

**Comment by clarkwang** [comment]
You can go ahead and get the diff and apply on your repo. It's ok for me.

**Comment by clarkwang** [comment]
Will create a feature branch for `--sedbin` and make a new pull request. Closing this confusing one.

**Comment by aureliojargas** [comment]
Superseded by #75 

Thanks @clarkwang for taking care of this.

**Pull request closed without merging**
